---
- hosts: all
  sudo: true
  tasks:
    - name: update apt cache
      apt: update_cache=yes
    - name: Install python packages
      apt: pkg={{item}} state=installed
      with_items:
      - python-dev
      - python-pip
      - python-beautifulsoup
      - python-requests
      - ipython
      - openjdk-7-jre
    - name: Create crispr directory
      file: path={{item}} state=directory
      with_items:
      - /vagrant/CRISPR-Genomics/crispr
      - /vagrant/CRISPR-Genomics/genomes
      - /vagrant/CRISPR-Genomics/crispr-hits
      - /vagrant/CRISPR-Genomics/reports
      - /vagrant/CRISPR-Genomics/annotations
