import re
import os

# variables to fill in
# path = file path of report generated by pilercr
path = "crispr/AC_000091.txt"


########## CRISPR region ##########

file = open(path, "r")
lst = file.read()

# if report does not contain CRISPR array, "SUMMARY BY POSITION" will not exists,
# return file name: No CRISPR array found
if bool(re.search("SUMMARY BY POSITION", lst)) == False:
	print os.path.basename(path) + ": No CRISPR array found"

else:
	lst = lst.split('SUMMARY BY POSITION')[1]
	lst = lst.split('\n')

	print "*********************************"
	print "Positions of CRISPR arrays:"
	print "Start position <space> end position"
	print "*********************************"
	print "File: " + os.path.basename(path) + '\n'

	for line in lst:
		# pos = lines with [numbers][>= 1 space][numbers]
		pos = re.findall('[0-9]+(?:\s+|$)[0-9]+', line)
		if pos != []:
				a = re.split(" +",pos[0])
				# start = start position of each CRISPR array in genome
				# end = end position of each CRISPR array in genome
				start = int(a[0])
				end = int(a[0]) + int(a[1])
				print start, end


file.close()